const items = [
    { name: 'Rose', cost: 1 },
    { name: 'TikTok', cost: 1 },
    { name: 'Chili', cost: 1 },
    { name: 'Weights', cost: 1 },
    { name: 'GG', cost: 1 },
    { name: 'Ice Cream Cone', cost: 1 },
    { name: 'Lightning Bolt', cost: 1 },
    { name: 'Enjoy Music', cost: 1 },
    { name: 'Mini Speaker', cost: 1 },
    { name: "It's corn", cost: 1 },
    { name: 'Cat Paws', cost: 1 },
    { name: 'Earth', cost: 1 },
    { name: 'Soccer', cost: 1 },
    { name: 'Hi June', cost: 1 }, //assuming this is a calendar
    { name: 'Tennis', cost: 1 },
    { name: 'Sneakerhead', cost: 1 },
    { name: 'Basketball', cost: 1 },
    { name: 'Cloud Bread', cost: 1 },
    { name: 'Big Love', cost: 5 },
    { name: 'Wide Eye Wurstie', cost: 5 }, // hotdog
    { name: 'Cotton\'s Shell', cost: 5 },
    { name: 'Fire', cost: 5 },
    { name: 'Mic', cost: 5 },
    { name: 'Panda', cost: 5 },
    { name: 'Anemo Slime', cost: 5 },
    { name: 'Finger Heart', cost: 5 },
    { name: 'Chill', cost: 5 },
    { name: 'Telescope', cost: 5 },
    { name: 'Pumpkin Pie', cost: 5 },
    { name: 'Football', cost: 5 },
    { name: 'Guacamole', cost: 6 },
    { name: 'Nachos', cost: 9 },
    { name: 'Taco', cost: 9 },
    { name: 'Hand Wave', cost: 9 },
    { name: 'Hi Bear', cost: 10 },
    { name: 'Stars Snap', cost: 10 },
    { name: 'Tiny Diny', cost: 10 },
    { name: 'Rosa', cost: 10 },
    { name: 'Lollipop', cost: 10 },
    { name: 'Gamepad', cost: 10 },
    { name: 'Balloons', cost: 10 },
    { name: 'Chicken Leg', cost: 10 },
    { name: 'Ticket', cost: 10 },
    { name: 'Tucker the Turkey', cost: 10 }, // turkey
    { name: 'ASMR Time', cost: 10 },
    { name: 'Pretzel', cost: 10 },
    { name: 'Mate tea', cost: 10 },
    { name: 'Rugby Ball', cost: 10 },
    { name: "Raccoon", cost: 15 },
    { name: "Cake", cost: 20 },
    { name: "Perfume", cost: 20 },
    { name: "Sushi Set", cost: 20 },
    { name: "Choco Strawberries", cost: 30 },
    { name: "Mirror", cost: 30 },
    { name: "Doughnut", cost: 30 },
    { name: "Pizza", cost: 40 },
    { name: "Football Helmet", cost: 50 },
    { name: "Boxing Robe", cost: 99 },
    { name: "Guitar", cost: 99 },
    { name: "Hat and Mustache", cost: 99 },
    { name: "Cap", cost: 99 },
    { name: "Little Crown", cost: 99 },
    { name: "Paper Crane", cost: 99 },
    { name: "Hand Heart", cost: 100 },
    { name: "Hand Hearts", cost: 100 },
    { name: "Confetti", cost: 100 },
    { name: "Flowers", cost: 100 },
    { name: "Butterfly", cost: 169 },
    { name: "Music Note", cost: 169 },
    { name: "Hearts", cost: 199 },
    { name: "Sunglasses", cost: 199 },
    { name: "Garland Headpiece", cost: 199 },
    { name: "Crown", cost: 199 },
    { name: "Goggles", cost: 199 },
    { name: "Knight Helmet", cost: 199 },
    { name: "Lock and Key", cost: 199 },
    { name: "Hanging Lights", cost: 199 },
    { name: "Gamer Cat", cost: 199 },
    { name: "Panther Paws", cost: 199 },
    { name: "The Passion Rose", cost: 199 },
    { name: "Mariachi Hat", cost: 199 },
    { name: "Love Focus", cost: 199 },
    { name: "Chef's Kiss", cost: 199 },
    { name: "Fruits Hat", cost: 199 },
    { name: "Kite", cost: 199 },
    { name: "Tulip Box", cost: 200 },
    { name: "Rose Bear", cost: 214 },
    { name: "Pancake", cost: 250 },
    { name: "FrankTasic", cost: 299 },
    { name: "Henry the Hedgehog", cost: 299 },
    { name: "Dancing Cactus", cost: 299 },
    { name: "Elephant trunk", cost: 299 },
    { name: "Corgi", cost: 299 },
    { name: "Duck", cost: 299 },
    { name: "Superpower", cost: 299 },
    { name: "Boxing Gloves", cost: 299 },
    { name: "Rock 'n' Roll", cost: 299 },
    { name: "Crystal Shoe", cost: 299 },
    { name: "Sail Away", cost: 299 },
    { name: "Lucy the Llama", cost: 299 },
    { name: "Gus the Groundhog", cost: 299 },
    { name: "Pawfect", cost: 299 },
    { name: "Classic Breakfast", cost: 299 },
    { name: "Air Dancer", cost: 300 },
    { name: "Birthday Cake", cost: 300 },
    { name: "Cotton the Seal", cost: 399 },
    { name: "Swing", cost: 399 },
    { name: "Necklace", cost: 400 },
    { name: "Coral", cost: 499 },
    { name: "Money Gun", cost: 500 },
    { name: "Owl", cost: 500 },
    { name: "Let's Go", cost: 500 },
    { name: "Quarterback Frank", cost: 500 },
    { name: "Falling For You", cost: 500 },
    { name: "LIVE Fest Trophy", cost: 699 },
    { name: "Dance Together", cost: 699 },
    { name: "Swan", cost: 699 },
    { name: "Piñta", cost: 699 },
    { name: "Candy Cane Gun", cost: 799 },
    { name: "Pearl", cost: 800 },
    { name: "Train", cost: 899 },
    { name: "LOVE U", cost: 899 },
    { name: "Travel with You", cost: 999 },
    { name: "Hot Air Balloon", cost: 999 },
    { name: "Dynamic Duo", cost: 1000 },
    { name: "Watermelon Love", cost: 1000 },
    { name: "Dinosaur", cost: 1000 },
    { name: "Mirror Bloom", cost: 1000 },
    { name: "Galaxy", cost: 1000 },
    { name: "Gold Mine", cost: 1000 },
    { name: "Email Message", cost: 1000 },
    { name: "Disco ball", cost: 1000 },
    { name: "Feather Flock", cost: 1000 },
    { name: "Fireworks", cost: 1088 },
    { name: "Arcade Game", cost: 1200 },
    { name: "Gaming Chair", cost: 1200 },
    { name: "Counting Sheep", cost: 1200 },
    { name: "Bumper Cars", cost: 1288 },
    { name: "Floral Bloom", cost: 1500 },
    { name: "Shooting Stars", cost: 1500 },
    { name: "Chasing the Dream", cost: 1500 },
    { name: "Garland", cost: 1500 },
    { name: "Champion", cost: 1500 },
    { name: "ASMR Starter Kit", cost: 1599 },
    { name: "Speedboat", cost: 1888 },
    { name: "Cooper Files Home", cost: 1999 },
    { name: "Make-up Box", cost: 1999 },
    { name: "Mystery Firework", cost: 1999 },
    { name: "Star Adventures", cost: 1999 },
    { name: "Rabbit", cost: 1999 },
    { name: "Fall Candle", cost: 1999 },
    { name: "Motorcycle", cost: 2988 },
    { name: "Whale diving", cost: 2150 },
    { name: "Concert", cost: 2888 },
    { name: "Mermaid", cost: 2988 },
    { name: "Meteor Shower", cost: 3000 },
    { name: "Ferris Wheel", cost: 3000 },
    { name: "Potluck", cost: 3000 },
    { name: "Giant", cost: 3999 },
    { name: "Show Time", cost: 3999 },
    { name: "Flower Overflow", cost: 4000 },
    { name: "UFO Landing", cost: 4000 },
    { name: "Restaurants", cost: 4000 },
    { name: "Island of Love", cost: 4000 },
    { name: "Knight", cost: 4088 },
    { name: "Leon the Kitten", cost: 4888 },
    { name: "Private Jet", cost: 4888 },
    { name: "Pool Party", cost: 4999 },
    { name: "Dancing Adam", cost: 5000 },
    { name: "Draco", cost: 5000 },
    { name: "Unicorn Fantasy", cost: 5000 },
    { name: "Valley Festival", cost: 5999 },
    { name: "Cooper's Home", cost: 5999 },
    { name: "Magic Forest", cost: 6000 },
    { name: "The Observatory", cost: 6999 },
    { name: "Beauty", cost: 6999 },
    { name: "Party Bus", cost: 7000 },
    { name: "Sports Car", cost: 7000 },
    { name: "Beach House", cost: 9999 },
    { name: "Yacht", cost: 9888 },
    { name: "Interstellar", cost: 10000 },
    { name: "Sunset Speedway", cost: 10000 },
    { name: "Camping Night", cost: 13999 },
    { name: "Leopard", cost: 15000 },
    { name: "Planet", cost: 15000 },
    { name: "Happy Train", cost: 15000 },
    { name: "American Eagle", cost: 19999 },
    { name: "Castle Fantasy", cost: 20000 },
    { name: "TikTok Shuttle", cost: 20000 },
    { name: "Phoenix", cost: 25999 },
    { name: "Adam's Dream", cost: 25999 },
    { name: "Dragon Flame", cost: 26999 },
    { name: "Lion", cost: 29999 },
    { name: "Same the Whale", cost: 30000 },
    { name: "Zeus", cost: 34000 },
    { name: "Leon and Lion", cost: 34000 },
    { name: "Seal and Whale", cost: 34500 },
    { name: "TikTok Universe", cost: 34999 },
    { name: "TikTok Stars", cost: 39999 }
];